version: '2'

services:
  elasticsearch-service:
    container_name: elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes: 
      - ${elasticsearch_data}:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      ELK_STACK: "true"
    networks:
      default:
        aliases:
          - elasticsearch
  kibana-service:
    container_name: kibana-service
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports: 
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/
    labels:
      ELK_STACK: "true"
  logstash-service:
    container_name: logstash-service
    image: docker.elastic.co/logstash/logstash:7.10.2
    volumes:
      - ./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/patterns/:/etc/logstash/patterns/
      - ${workdir}:/mnt/workdir/
    ports:
      - 9600:9600
      - "5044:5044/tcp"
      - "5044:5044/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    labels:
      ELK_STACK: "true"
